# xsens_mti630.yaml parameter server

# Example configuration
# 
# linear_acceleration_mean: Average noise (micrograms), (should be 0)
# linear_acceleration_std: Average noise density (micrograms/sqrt(Hz)),
# angular_velocity_mean: Average angular velocity mean (degrees/s), (should be 0)
# angular_velocity_std: Average angular velocity noise density (milli-degrees/(s*sqrt(Hz))),
# orientation_mean: Average angle (degrees), (should be 0)
# orientation_std: Average angle standard deviation (degrees)
#  
# These units are converted to the ROS standard units internally. 
# The units above are standard for IMU/AHRS datasheets.

profile: xsens_mti_630
frequency: 100

noise_type: gaussian

noise_types:
  - gaussian

tf_prefix: alpha

link_name: imu

linear_acceleration_mean: 0
linear_acceleration_std: 60

angular_velocity_mean: 0
angular_velocity_std: 7

orientation_mean: 0
orientation_std: 0.05