port: /dev/ttyACM0

pwm_control:
  pwm_chan0:
    channel: 0
    mode: thruster
    topic: control/pwm_chan0

  pwm_chan1:
    channel: 1
    mode: thruster
    topic: control/pwm_chan1

  pwm_chan2:
    channel: 2
    mode: thruster
    topic: control/pwm_chan2

  pwm_chan3:
    channel: 3
    mode: thruster
    topic: control/pwm_chan3

  pwm_chan4:
    channel: 4
    mode: thruster
    topic: control/pwm_chan4
