# Minimum and maximum positions for each degree of freedom (DOF)
max_pos: [10.0, 10.0, 10.0, 3.14159265359, 3.14159265359, 3.14159265359]
min_pos: [-10.0, -10.0, -10.0, -3.14159265359, -3.14159265359, -3.14159265359]

# Minimum and maximum velocities for each degree of fredom (m/s or rad/s)
max_vel: [0.5, 0.5, 0.35, 0.0, 0.3, 0.3]
min_vel: [-0.25, 0.5, -0.35, 0.0, 0.3, -0.3]

# Initial state of the controllers (pose vs. velocity)
pose_controlled_axis: [false, false, false, false, false, false]

# Initial pose for the pose controllers
base_pose: [0, 0, 0, 0, 0, 0]

# Use current pose as base pose when the pose controllers are activated
actualize_base_pose: true
