main:
  type: topic
  message_type: std_msgs/Float64
  topic_name: control/thruster/main
  deadman_buttons: [4]
  axis_mappings:
    -
      axis: 1
      target: data
      scale: 1
      offset: 0

horizontal:
  type: topic
  message_type: std_msgs/Float64
  topic_name: control/thruster/horizontal
  deadman_buttons: [4]
  axis_mappings:
    -
      axis: 3
      target: data
      scale: 1
      offset: 0

vertical:
  type: topic
  message_type: std_msgs/Float64
  topic_name: control/thruster/vertical
  deadman_buttons: [4]
  axis_mappings:
    -
      axis: 4
      target: data
      scale: 1
      offset: 0


led:
  type: topic
  message_type: std_msgs/Float64
  topic_name: control/led
  deadman_buttons: [4]
  axis_mappings:
    -
      axis: 2
      target: data
      scale: -0.5
      offset: 0.5

led2:
  type: topic
  message_type: std_msgs/Float64
  topic_name: control/led2
  deadman_buttons: [4]
  axis_mappings:
    -
      axis: 5
      target: data
      scale: -0.5
      offset: 0.5

