##
#
# List of user defined modes. Each mode has to be
# defined under "control_rules" variable.
#
##
control_modes:
  - flight
  - hold

##
#
# Control rules for each control mode
# Possible values for control rules are
# - x
# - y
# - z
# - roll
# - pitch
# - yaw
# - u
# - v
# - w
#
##
control_rules:
  flight:
    - u
    - pitch
    - yaw

  hold:
    - x
    - y
    - z
    - pitch
    - yaw