##
# PID gains for each degree of freedom
##
pid:
  x:      {p: 3.0,    i: 0.5,   d: 5.0,   i_max: 10, i_min: -10}
  y:      {p: 3.0,    i: 0.5 ,  d: 5.0,   i_max: 10, i_min: -10}
  z:      {p: 5.0,    i: 1.0 ,  d: 10.0,  i_max: 10, i_min: -10}
  roll:   {p: 0.0,    i: 0.0,   d: 0.0,   i_max: 10, i_min: -10}
  pitch:  {p: 10.0,   i: 1.0,   d: 5.0,   i_max: 10, i_min: -10}
  yaw:    {p: 10.0,   i: 1.0,   d: 5.0,   i_max: 20, i_min: -20}
  u:      {p: 100.0,  i: 3.0,   d: 5.0,   i_max: 10, i_min: -10}
  v:      {p: 5.0,    i: 4.0,   d: 1.0,   i_max: 10, i_min: -10}
  w:      {p: 5.0,    i: 4.0,   d: 1.0,   i_max: 10, i_min: -10}
