frequency: 10
sensor_timeout: 0.1
two_d_mode: false
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
debug: false



##
# in seconds
#
history_length: 10.0

#   [     X,        Y,        Z,
#      roll,    pitch,      yaw,
#       V_x,      V_y,      V_z,
#    V_roll,  V_pitch,    V_yaw,
#        ax,       ay,       az]

# odom0: /odometry/filtered/local
# odom0_config: [false, false, true,
#                true, true, true,
#                true, true, true,
#                true, true, true,
#                true, true, true]
# odom0_queue_size: 10
# odom0_nodelay: true
# odom0_differential: false
# odom0_relative: false

# odom1: /odometry/gps
# odom1_config: [true, true, false,
#                false, false, false,
#                false, false, false,
#                false, false, false,
#                false, false, false]
# odom1_queue_size: 10
# odom1_nodelay: true
# odom1_differential: false
# odom1_relative: false


process_noise_covariance: [1e-1, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    1e-1, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0.0001,  0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0.001,  0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0.001,  0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0.001,  0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0.001,   0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0.001,   0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0.001,  0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0.001,  0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01,  0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.01,  0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.1,  0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.1,  0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.1]

# odom0: odometry/gps
# odom0_config: [true,  true,  false,
#                 false, false, false,
#                 false, false, false,
#                 false, false, false,
#                 false, false, false]
# odom0_queue_size: 10
# odom0_nodelay: true
# odom0_differential: false
# odom0_relative: false

# odom1: odometry/filtered/local
# odom1_config: [false, false, true,
#                 false, false, false,
#                 true,  true,  true,
#                 false, false, false,
#                 false, false, false]
# odom1_queue_size: 10
# odom1_nodelay: true
# odom1_differential: false
# odom1_relative: false


# imu0: imu/data
# imu0_config: [false, false, false,
#               true,  true,  true,
#               false, false, false,
#               true,  true,  true,
#               true,  true,  true]
# imu0_nodelay: true
# imu0_differential: false
# imu0_relative: false
# imu0_queue_size: 10
# imu0_remove_gravitational_acceleration: false