
##
# State estimation frequency
#
frequency: 10
sensor_timeout: 2.0

two_d_mode: true

transform_time_offset: 1.0
transform_timeout: 0.0
print_diagnostics: true
debug: true
publish_tf: true
publish_acceleration: false

##
# in seconds
#
history_length: 10.0

#   [     X,        Y,        Z,
#      roll,    pitch,      yaw,
#       V_x,      V_y,      V_z,
#    V_roll,  V_pitch,    V_yaw,
#        ax,       ay,       az]

odom0: /odometry/gps
odom0_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_pose_use_child_frame: false
odom0_nodelay: true

odom1: /odometry/filtered/local
odom1_config: [false, false, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]
odom1_differential: false
odom1_queue_size: 100
odom1_nodelay: true

# process_noise_covariance: [1e-1, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    1e-1, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0.0001,  0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0.001,  0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0.001,  0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0.001,  0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0.001,   0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0.001,   0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0.001,  0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0.001,  0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01,  0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.01,  0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.1,  0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.1,  0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.1]