
##
# State estimation frequency
#
frequency: 20
sensor_timeout: 2.0

##
# 2 dimentional mode
#
two_d_mode: false


transform_time_offset: 1.0
transform_timeout: 0.0
print_diagnostics: true
debug: false
publish_tf: false
publish_acceleration: true

##
# in seconds
#
history_length: 5.0

odom0: /odometry/local
odom0_config: [true, true, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]

odom0_differential: false

odom1: /odometry/gps
odom1_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_differential: false