generator_type: tf

control_tf:
  main: main_thruster_link
  horizontal: horizontal_thruster_link
  vertical: vertical_thruster_link

tf_prefix: alpha

cg_link: cg_link

world_link: world_ned

odometry_source: /odometry/filtered

enabled: true

control_modes:
  teleop:
    surge:      {p: 1.0,  i: 3.0,   d: 5.0,  i_max: 10, i_min: -10}
    yaw_rate:   {p: 2.0,  i: 0.5,   d: 3.0,  i_max: 20, i_min: -20}
    pitch_rate: {p: 2.0,  i: 0.5,   d: 3.0,  i_max: 20, i_min: -20}

  heading:
    yaw:      {p: 20.0,  i: 0.5,   d: 30.0,  i_max: 20, i_min: -20}

  flight:
    pitch:    {p: 5.0,    i: 1.0,   d: 2.0,   i_max: 10, i_min: -10}
    yaw:      {p: 5.0,    i: 0.5,   d: 30.0,  i_max: 20, i_min: -20}
    surge:    {p: 10.0,   i: 3.0,   d: 5.0,   i_max: 10, i_min: -10}

  hold:
    x:        {p: 1.0,    i: 0.5,   d: 1.0,   i_max: 10, i_min: -10}
    y:        {p: 1.0,    i: 0.5 ,  d: 1.0,   i_max: 10, i_min: -10}
    z:        {p: 1.0,    i: 1.0 ,  d: 10.0,  i_max: 10, i_min: -10}
    pitch:    {p: 5.0,    i: 1.0,   d: 2.0,   i_max: 10, i_min: -10}
    yaw:      {p: 5.0,    i: 0.5,   d: 30.0,  i_max: 20, i_min: -20}

  kill: false


##
# THRUSTERS
##
thruster_ids:
  - main
  - horizontal
  - vertical

thruster_command_topics:
  main: control/thruster/main
  horizontal: control/thruster/horizontal
  vertical: control/thruster/vertical

thruster_force_topics:
  main: control/force/main
  horizontal: control/force/horizontal
  vertical: control/force/vertical


##
# Polynomials for each thruster.
#
# Quadratic Programming Optimization computes the thrust
# required. We need to turn that number into thruster command.
# Setpoint commands in this system defined between -1 and 1.
#
# y axis of the polynomial , f(x) = y, should be in Newton.
#
# Take the polynomial
# f(x) = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0
#
# Array would hold the lower degrees in lower indexes. Shown below:
# [a_0, a_1, ... ,a_(n-1), a(n)]
#
# For T200 bluerobotics thrusters:
#   f(x) = a5*x^5 + a4*x^4 + a3*x^3 + a2*x^2 + a1*x + a0
# Curve fitting results:
#   a0 =      0.06165
#   a1 =      20.32
#   a2 =      9.632
#   a3 =      93.05
#   a4 =      -2.856
#   a5 =      -74.1
##
thruster_polynomials:
  main:       [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  horizontal: [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  vertical:   [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]

