port: /dev/PICO

pwm_control:
  surge:
    channel: 2
    mode: thruster
    topic: control/thruster/surge

  sway:
    channel: 3
    mode: thruster
    topic: control/thruster/sway

  heave_bow:
    channel: 4
    mode: thruster
    topic: control/thruster/heave_bow

  heave_stern:
    channel: 1
    mode: pure
    topic: control/thruster/heave_stern
