port: /dev/PICO

pwm_control:
  main:
    channel: 2
    mode: thruster
    topic: control/thruster/main

  horizontal:
    channel: 3
    mode: thruster
    topic: control/thruster/horizontal

  vertical:
    channel: 4
    mode: thruster
    topic: control/thruster/vertical

  led:
    channel: 1
    mode: pure
    topic: control/led
