# Image size and type
width: 1920
height: 1080
video_mode: mjpeg
frame_rate: 10

# parameters to find the camera
vendor: "0x0c45"
product: "0x6366"

# Other
auto_exposure: 3
auto_white_balance: false
timestamp_method: start