period: 0.1
n_thrusters: 3

# Thruster control matrix. This matrix specifies how each thruster contributes
# to the force or torque generated in each axis of the robot
TCM: [
  1.0, 0.0, 0.0,
  0.0, 1.0, 0.0,
  0.0, 0.0, 1.0,
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.46,
  0.0, 0.36, 0.0
]

# Thruster 1 - main thruster
thruster_1_poly_positive: [0.03195, 0.03596, -0.0005826, 0.000004209]  # Positive sign in serial port string, means robot moves backwards
thruster_1_poly_negative: [-0.018, 0.04538, 0.00087, 0.000007134]  # Negative sign in serial port string, means robot moves forward
thruster_1_max_force_positive: 60.0
thruster_1_max_force_negative: 50.0

# Thruster 2 - horizontal tunnel
thruster_2_poly_positive: [0.03195, 0.03596, -0.0005826, 0.000004209]  # Positive sign in serial port string, means robot moves backwards
thruster_2_poly_negative: [-0.018, 0.04538, 0.00087, 0.000007134]  # Negative sign in serial port string, means robot moves forward
thruster_2_max_force_positive: 60.0
thruster_2_max_force_negative: 50.0

# Thruster 3 - vertical tunnel
thruster_3_poly_positive: [0.03195, 0.03596, -0.0005826, 0.000004209]  # Positive sign in serial port string, means robot moves backwards
thruster_3_poly_negative: [-0.018, 0.04538, 0.00087, 0.000007134]  # Negative sign in serial port string, means robot moves forward
thruster_3_max_force_positive: 60.0
thruster_3_max_force_negative: 50.0


# Enbale thrusters
enable_thrusters: false


# Maximum velocity for each DOF
max_velocity_x: 0.8
max_velocity_y: 0.0
max_velocity_z: 0.1
max_velocity_roll: 0.0
max_velocity_pitch: 0.7
max_velocity_yaw: 0.7

# Set zero velocity parameters
set_zero_velocity_depth: 10.0
set_zero_velocity_axes: [true, false, true, false, true, true]


# POSE PID CONTROLLER
# The following parameters adjust the proportional–integral–derivative
# controllers for each degree of freedom (DOF). i_limit represents the maximum
# value the integral part can take (anti-windup), and fff allows a feed-forward
# force to be specified (sometimes useful for the heave controller)
p_surge_kp: 0.0
p_surge_ti: 0.0
p_surge_td: 0.0
p_surge_i_limit: 0.0
p_surge_fff: 0.0

p_sway_kp: 0.0
p_sway_ti: 0.0
p_sway_td: 0.0
p_sway_i_limit: 0.0
p_sway_fff: 0.0

p_heave_kp: 1.2
p_heave_ti: 0.0
p_heave_td: 0.0
p_heave_i_limit: 0.0
p_heave_fff: 0.0

p_roll_kp: 0.0
p_roll_ti: 0.0
p_roll_td: 0.0
p_roll_i_limit: 0.0
p_roll_fff: 0.0

p_pitch_kp: 1.0
p_pitch_ti: 0.0
p_pitch_td: 0.0
p_pitch_i_limit: 0.0
p_pitch_fff: 0.0

p_yaw_kp: 0.5
p_yaw_ti: 0.0
p_yaw_td: 2.0
p_yaw_i_limit: 0.0
p_yaw_fff: 0.0


# Twist (velocity) PID controller
t_surge_kp: 0.25
t_surge_ti: 20.0
t_surge_td: 0.0
t_surge_i_limit: 0.25
t_surge_fff: 0.0

t_sway_kp: 1.0
t_sway_ti: 0.0
t_sway_td: 0.0
t_sway_i_limit: 1.0
t_sway_fff: 0.0

t_heave_kp: 0.95
t_heave_ti: 0.1
t_heave_td: 0.0
t_heave_i_limit: 0.15
t_heave_fff: 0.1

t_roll_kp: 0.0
t_roll_ti: 0.0
t_roll_td: 0.0
t_roll_i_limit: 1.0
t_roll_fff: 0.0

t_pitch_kp: 1.0
t_pitch_ti: 0.0
t_pitch_td: 0.0
t_pitch_i_limit: 1.0
t_pitch_fff: 0.0

t_yaw_kp: 2.5
t_yaw_ti: 8.0
t_yaw_td: 0.0
t_yaw_i_limit: 0.15
t_yaw_fff: 0.0


# Parameters for a feed-forward polynomial model for each DOF (A+B*x+C*x^2)
poly_surge_A: 0.0
poly_surge_B: 0.0
poly_surge_C: 25.0

poly_sway_A: 0.0
poly_sway_B: 0.0
poly_sway_C: 25.0

poly_heave_A: 0.0
poly_heave_B: 4.0
poly_heave_C: 250.0

poly_roll_A: 0.0
poly_roll_B: 0.0
poly_roll_C: 0.0

poly_pitch_A: 0.0
poly_pitch_B: 0.0
poly_pitch_C: 0.25

poly_yaw_A: 0.0
poly_yaw_B: 0.0
poly_yaw_C: 10.8


# Maximum wrench (force) for each DOF
max_wrench_X: 154.0
max_wrench_Y: 30.0
max_wrench_Z: 30.0
max_wrench_Roll: 0.00
max_wrench_Pitch: 17.15
max_wrench_Yaw: 14.43