# Determine the publish rate of the diagnostics aggregator
pub_rate: 2.0

# The following parameters are used to categorize the data from the diagnostics
# in order to display the desired hierarchy in the robot_monitor tool
base_path: ''
analyzers:
  safety:
    type: diagnostic_aggregator/GenericAnalyzer
    path: safety
    name:
      - 'batteries'
      - 'main_control_board'
      - 'battery_control_board'
      - 'virtual_cage'
      - 'safe_depth_altitude'
      - 'watchdog_timer'
      - 'comms'
      # - 'modem'
      - 'computer_logger'
      - 'param_logger'
      - 'safety_supervisor_checker'

  navigation:
    type: diagnostic_aggregator/GenericAnalyzer
    path: navigation
    name:
      - 'pressure'
      - 'imu'
      - 'imu_filter'
      - 'gps'
      - 'dvl'
      - 'navigator'

  control:
    type: diagnostic_aggregator/GenericAnalyzer
    path: control
    name:
      - 'controller'
      # - 'teleoperation'
      - 'captain'
      - 'pilot'
      - 'thrusters'
