# Sensor publication periods
gps_period: 1.0
depth_period: 0.2
dvl_period: 0.2
imu_period: 0.05
usbl_period: 0.0

# Other
sea_bottom_depth: 20.0
sound_speed: 1500
usbl_depth_start: 2.0

# Sensors covariances (simulated error). Covariances are the squared value of the measurement's standard deviation.
gps_position_covariance: [1.0, 1.0]
depth_pressure_covariance: 10000.0  # in pascals (approx 0.01 meters)
dvl_velocity_covariance: [0.00000225, 0.00000225, 0.00000225]
imu_orientation_covariance: [0.00000001, 0.00000001, 0.00000001]
usbl_position_covariance: 1.0

# Sensors covariances (message covariance). Covariances are the squared value of the measurement's standard deviation.
output_gps_position_covariance: [9.0, 9.0]
output_depth_pressure_covariance: 1000000.0  # in pascals (approx 0.1 meters, 0.1m = 1000 pascals --> 1000^2 pascals)
output_dvl_velocity_covariance: [0.04, 0.04, 0.04]
output_imu_orientation_covariance: [0.01, 0.01, 0.01]
output_usbl_position_covariance: 9.0
