# waterlink_a50.yaml parameter configuration

# Example configuration
# velocity_average_percent_err: assuming a uniform bias above and below the actual, this is just a plus/minus percent
# distance_average_percent_err: assuming a uniform bias above and below the actual, this is just a plus/minus percent
# dvl_max_range: This is the maximum range of a non-ACDP DVL, in which it needs to be a certain distance from the target (seafloor). 

profile: waterlink_a50
ping_rate: 100

noise_type: uniform

noise_types:
  - uniform

tf_prefix: alpha

link_name: dvl

velocity_average_percent_err: 1.1 #plus/minus
distance_average_percent_err: 1.1 #plus/minus
dvl_max_range: 50 #meters
seafloor_depth: 50 #meters


